<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>click_keranjang</name>
   <tag></tag>
   <elementGuidId>6c4f20cd-4810-4034-8b0b-2ed679f76c41</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@id = 'shopping_cart_container']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>99291a5c-d015-4203-8015-67b87b7eedfc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>shopping_cart_container</value>
      <webElementGuid>2b95f78d-e794-4a11-9e42-43bc2b93226e</webElementGuid>
   </webElementProperties>
</WebElementEntity>
