<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>click_keranjang</name>
   <tag></tag>
   <elementGuidId>94c5a0fd-5652-4349-a32f-090e5520624d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@id = 'shopping_cart_container']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>3f2bbc3b-a335-427c-9c78-989c0425b396</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>shopping_cart_container</value>
      <webElementGuid>c289cc79-7b91-4cae-8b40-cba4979b227b</webElementGuid>
   </webElementProperties>
</WebElementEntity>
