<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>click_addToCart</name>
   <tag></tag>
   <elementGuidId>9d5aad3c-431b-4a3c-9a00-5856a1fe7113</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//button[@id = 'add-to-cart-sauce-labs-bolt-t-shirt']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>51a6dae7-f5f7-4c81-b1f1-f1a1a6699c20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>add-to-cart-sauce-labs-bolt-t-shirt</value>
      <webElementGuid>2d732a22-55f9-460d-9f14-d62082f9fd96</webElementGuid>
   </webElementProperties>
</WebElementEntity>
